version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      READER_USER: reader
      READER_PASSWORD: reader
      UPDATER_USER: updater
      UPDATER_PASSWORD: updater

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1