#database
CREATE DATABASE app_db;

#countries
CREATE TABLE app_db.COUNTRIES (ID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(100) NOT NULL UNIQUE);
ALTER TABLE `app_db`.`COUNTRIES` ADD INDEX `ID_INDEX` (`ID`);

#patients
CREATE TABLE `app_db`.`PATIENTS` (`ID` INT NOT NULL AUTO_INCREMENT , `CODE` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , PRIMARY KEY (`ID`), UNIQUE (`CODE`(50))) ENGINE = InnoDB;
ALTER TABLE `app_db`.`PATIENTS` ADD INDEX `ID_INDEX` (`ID`);

#medicines
CREATE TABLE `app_db`.`MEDICINES` (`ID` INT NOT NULL AUTO_INCREMENT , `NAME` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL , PRIMARY KEY (`ID`), UNIQUE (`NAME`(100))) ENGINE = InnoDB;
ALTER TABLE `app_db`.`MEDICINES` ADD INDEX `ID_INDEX` (`ID`);

#read users
CREATE USER 'reader'@'%' IDENTIFIED BY 'reader';
GRANT SELECT ON app_db.* TO 'reader'@'%';
FLUSH PRIVILEGES;

#insert users
CREATE USER 'updater'@'%' IDENTIFIED BY 'updater';
GRANT INSERT, UPDATE ON app_db.* TO 'updater'@'%';
FLUSH PRIVILEGES;

#PURCHASES
CREATE TABLE `app_db`.`PURCHASES` (`ID` INT NOT NULL AUTO_INCREMENT , `PATIENT_ID` INT NOT NULL , `COUNTRY_ID` INT NOT NULL , `MEDICINE_ID` INT NOT NULL , `QUANTITY` INT NOT NULL , `PURCHASE_DATE` TIMESTAMP NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
ALTER TABLE `PURCHASES` ADD CONSTRAINT `FK_PURCHASES_PATIENT` FOREIGN KEY (`PATIENT_ID`) REFERENCES `PATIENTS`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 
ALTER TABLE `PURCHASES` ADD CONSTRAINT `FK_PURCHASES_COUNTRY` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRIES`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 
ALTER TABLE `PURCHASES` ADD CONSTRAINT `FK_PURCHASES_MEDICINE` FOREIGN KEY (`MEDICINE_ID`) REFERENCES `MEDICINES`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `app_db`.`PURCHASES` ADD INDEX `ID_INDEX` (`ID`);
ALTER TABLE `app_db`.`PURCHASES` ADD INDEX `INDEX_SEARCH` (`PATIENT_ID`, `COUNTRY_ID`, `MEDICINE_ID`);

#prices
CREATE TABLE PRICES (ID INT AUTO_INCREMENT PRIMARY KEY, COUNTRY_ID INT, YEAR INT,  MEDICINE_ID INT, PRICE DECIMAL(10, 2), CONSTRAINT UC_YEAR_MEDICINE UNIQUE (YEAR, MEDICINE_ID, COUNTRY_ID)); 
ALTER TABLE `PRICES` ADD CONSTRAINT `FK_PRICES_COUNTRIES` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRIES`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 
ALTER TABLE `PRICES` ADD CONSTRAINT `FK_PRICES_MEDICINES` FOREIGN KEY (`MEDICINE_ID`) REFERENCES `MEDICINES`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `app_db`.`PRICES` ADD INDEX `ID_INDEX` (`ID`);
ALTER TABLE `app_db`.`PRICES` ADD INDEX `ID_SEARCH` (`COUNTRY_ID`, `MEDICINE_ID`);

